### ISSUE TITLE
Shared RMSProp

### ISSUE THREAD

**Issue by rbrigden** [rbrigden/a3c#3]
Implement shared RMS prop as described in [the paper](https://arxiv.org/abs/1602.01783)

- [x] Understand the "shared RMSprop" detailed in the paper

- [ ] Figure out if the tensorflow RMSprop works

- [ ] If tf.RMSprop isn't what we want, implement the paper version

**Comment by rbrigden** [comment]
Status @tonyf ?

**Comment by tonyf** [comment]
Verified current implementation is using shared version with subclass. Subclass checks if optimizer that is being called in worker is the global shared optimizer, and is updating its gradients, not its own.
