### ISSUE TITLE
Fix NAN disaster

### ISSUE THREAD

**Issue by remzr7** [rbrigden/a3c#5]
[https://trello-attachments.s3.amazonaws.com/58f3bfdea9b8b24f27f3e16c/58f51307d8e0182b128ff975/6d63600fd66902db8d4442beb2ff2764/Screen_Shot_2017-04-17_at_11.53.36_AM.png](url)

**Comment by rbrigden** [comment]
I fixed the NaN problem by implementing gradient clipping. However the issue remains that the policy becomes entirely deterministic (One of the actions gets a ~1.0 probability). Closing this issue and opening a new more specific one.
